name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install Dependencies
        run: npm install

      - name: Run tests
        run: npm run test:headless

      - name: Build
        run: npm run build:prod

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
   
      - name: Deploy 🚀
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          deploy_key: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/pokedex-angular
          external_repository: f3rjara/pokedex-angular
          enable_jekyll: true
          user_name: 'Fernando Jaramillo'
          user_email: 'f3rjara@gmail.com'
          commit_message: 'Deploying to gh-pages'
